
package cat.ehh.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * Fri Jan 15 16:35:58 CET 2016
 * Generated source version: 2.7.14.redhat-1
 */

@XmlRootElement(name = "addPatientGeofence", namespace = "http://ws.ehh.cat/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addPatientGeofence", namespace = "http://ws.ehh.cat/", propOrder = {"arg0", "arg1", "arg2", "arg3"})

public class AddPatientGeofence {

    @XmlElement(name = "patientId")
    private int arg0;
    @XmlElement(name = "radius")
    private int arg1;
    @XmlElement(name = "latitude")
    private double arg2;
    @XmlElement(name = "longitude")
    private double arg3;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

    public int getArg1() {
        return this.arg1;
    }

    public void setArg1(int newArg1)  {
        this.arg1 = newArg1;
    }

    public double getArg2() {
        return this.arg2;
    }

    public void setArg2(double newArg2)  {
        this.arg2 = newArg2;
    }

    public double getArg3() {
        return this.arg3;
    }

    public void setArg3(double newArg3)  {
        this.arg3 = newArg3;
    }

}

