
package cat.ehh.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * Sat Dec 19 08:47:49 CET 2015
 * Generated source version: 2.7.14.redhat-1
 */

@XmlRootElement(name = "initResponse", namespace = "http://ws.ehh.cat/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "initResponse", namespace = "http://ws.ehh.cat/")

public class InitResponse {


}

