
package cat.ehh.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * Mon Dec 21 11:59:10 CET 2015
 * Generated source version: 2.7.14.redhat-1
 */

@XmlRootElement(name = "sendPatientLocation", namespace = "http://ws.ehh.cat/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sendPatientLocation", namespace = "http://ws.ehh.cat/", propOrder = {"arg0", "arg1", "arg2", "arg3"})

public class SendPatientLocation {

    @XmlElement(name = "patientId")
    private int arg0;
    @XmlElement(name = "locationDate")
    private java.lang.String arg1;
    @XmlElement(name = "latitude")
    private float arg2;
    @XmlElement(name = "longitude")
    private float arg3;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

    public java.lang.String getArg1() {
        return this.arg1;
    }

    public void setArg1(java.lang.String newArg1)  {
        this.arg1 = newArg1;
    }

    public float getArg2() {
        return this.arg2;
    }

    public void setArg2(float newArg2)  {
        this.arg2 = newArg2;
    }

    public float getArg3() {
        return this.arg3;
    }

    public void setArg3(float newArg3)  {
        this.arg3 = newArg3;
    }

}

